---
name: TubeShaker
description: A new Flutter project.
publish_to: none
version: 1.0.0+9
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  http:
  provider:
  logger: "^0.9.4"
  shared_preferences: "^0.5.12+4"
  moor_flutter: "^3.1.0"
  json_serializable:
  flutter_inappwebview: "^4.0.0+4"
  receive_sharing_intent: "^1.4.2"
  html: "^0.14.0+4"
  fab_circular_menu: "^1.0.1"
  flutter_slidable: "^0.5.7"
  url_launcher: "^5.7.10"
  easy_localization:
  firebase_crashlytics:
  cupertino_icons: "^1.0.0"
  path_provider:
  sqlite3_flutter_libs:
  path:
  rxdart:
  share: "^0.6.5+4"
  firebase_dynamic_links:
  firebase_core: 0.5.0+1
  firebase_database:
  firebase_analytics: 5.0.16
  admob_flutter: "^1.0.1"
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  moor_generator: "^3.2.0"
  intl_translation: "^0.17.1"
  flutter_launcher_icons: "^0.8.0"
flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/icon/icon.png
flutter:
  uses-material-design: true
  assets:
  - assets/translations/
  - assets/admob/
